apiVersion: v1
kind: Service
metadata:
  name: phoenix-service  # ç»™æœåŠ¡èµ·ä¸ªæ­£å¼çš„åå­—
spec:
  type: NodePort         # ğŸ”¥ å…³é”®ï¼šæ”¹ä¸º NodePort ç±»å‹
  selector:
    app: phoenix         # åªè¦æ ‡ç­¾æ˜¯ app: phoenix çš„ Podï¼Œéƒ½æ˜¯æˆ‘çš„äºº
  ports:
    - protocol: TCP
      port: 80           # Service ä¹Ÿå°±æ˜¯è¿™ä¸ªâ€œè™šæ‹Ÿæ€»æœºâ€å¯¹å¤–æ˜¾ç¤ºçš„ç«¯å£
      targetPort: 5000   # è½¬å‘ç»™ Pod é‡Œçš„ 5000 ç«¯å£
      nodePort: 30007    # ğŸšª æŒ‡å®šå¢™ä¸Šçš„æ´ï¼š30000-32767 ä¹‹é—´ã€‚ä¸ºäº†å¥½è®°ï¼Œæˆ‘ä»¬é€‰ 30007
